//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtocolSigningService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.skyline.be/protocolsigning", ConfigurationName="ProtocolSigningService.SoapSoap")]
    public interface SoapSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skyline.be/protocolsigning/Connect", ReplyAction="*")]
        System.Threading.Tasks.Task<ProtocolSigningService.ConnectResponse> ConnectAsync(ProtocolSigningService.ConnectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skyline.be/protocolsigning/LogOut", ReplyAction="*")]
        System.Threading.Tasks.Task<ProtocolSigningService.LogOutResponse> LogOutAsync(ProtocolSigningService.LogOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skyline.be/protocolsigning/SignProtocolXmlFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ProtocolSigningService.SignProtocolXmlFileResponse> SignProtocolXmlFileAsync(ProtocolSigningService.SignProtocolXmlFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skyline.be/protocolsigning/SignProtocolZipFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ProtocolSigningService.SignProtocolZipFileResponse> SignProtocolZipFileAsync(ProtocolSigningService.SignProtocolZipFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skyline.be/protocolsigning/SignProtocolString", ReplyAction="*")]
        System.Threading.Tasks.Task<ProtocolSigningService.SignProtocolStringResponse> SignProtocolStringAsync(ProtocolSigningService.SignProtocolStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.skyline.be/protocolsigning/EncryptProtocolZipFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ProtocolSigningService.EncryptProtocolZipFileResponse> EncryptProtocolZipFileAsync(ProtocolSigningService.EncryptProtocolZipFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConnectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Connect", Namespace="http://www.skyline.be/protocolsigning", Order=0)]
        public ProtocolSigningService.ConnectRequestBody Body;
        
        public ConnectRequest()
        {
        }
        
        public ConnectRequest(ProtocolSigningService.ConnectRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.skyline.be/protocolsigning")]
    public partial class ConnectRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string domain;
        
        public ConnectRequestBody()
        {
        }
        
        public ConnectRequestBody(string userName, string password, string domain)
        {
            this.userName = userName;
            this.password = password;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConnectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConnectResponse", Namespace="http://www.skyline.be/protocolsigning", Order=0)]
        public ProtocolSigningService.ConnectResponseBody Body;
        
        public ConnectResponse()
        {
        }
        
        public ConnectResponse(ProtocolSigningService.ConnectResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.skyline.be/protocolsigning")]
    public partial class ConnectResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConnectResult;
        
        public ConnectResponseBody()
        {
        }
        
        public ConnectResponseBody(string ConnectResult)
        {
            this.ConnectResult = ConnectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogOutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogOut", Namespace="http://www.skyline.be/protocolsigning", Order=0)]
        public ProtocolSigningService.LogOutRequestBody Body;
        
        public LogOutRequest()
        {
        }
        
        public LogOutRequest(ProtocolSigningService.LogOutRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.skyline.be/protocolsigning")]
    public partial class LogOutRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string connectionGuid;
        
        public LogOutRequestBody()
        {
        }
        
        public LogOutRequestBody(string connectionGuid)
        {
            this.connectionGuid = connectionGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogOutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogOutResponse", Namespace="http://www.skyline.be/protocolsigning", Order=0)]
        public ProtocolSigningService.LogOutResponseBody Body;
        
        public LogOutResponse()
        {
        }
        
        public LogOutResponse(ProtocolSigningService.LogOutResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogOutResponseBody
    {
        
        public LogOutResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignProtocolXmlFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignProtocolXmlFile", Namespace="http://www.skyline.be/protocolsigning", Order=0)]
        public ProtocolSigningService.SignProtocolXmlFileRequestBody Body;
        
        public SignProtocolXmlFileRequest()
        {
        }
        
        public SignProtocolXmlFileRequest(ProtocolSigningService.SignProtocolXmlFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.skyline.be/protocolsigning")]
    public partial class SignProtocolXmlFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string connectionGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] protocol;
        
        public SignProtocolXmlFileRequestBody()
        {
        }
        
        public SignProtocolXmlFileRequestBody(string connectionGuid, byte[] protocol)
        {
            this.connectionGuid = connectionGuid;
            this.protocol = protocol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignProtocolXmlFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignProtocolXmlFileResponse", Namespace="http://www.skyline.be/protocolsigning", Order=0)]
        public ProtocolSigningService.SignProtocolXmlFileResponseBody Body;
        
        public SignProtocolXmlFileResponse()
        {
        }
        
        public SignProtocolXmlFileResponse(ProtocolSigningService.SignProtocolXmlFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.skyline.be/protocolsigning")]
    public partial class SignProtocolXmlFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] SignProtocolXmlFileResult;
        
        public SignProtocolXmlFileResponseBody()
        {
        }
        
        public SignProtocolXmlFileResponseBody(byte[] SignProtocolXmlFileResult)
        {
            this.SignProtocolXmlFileResult = SignProtocolXmlFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignProtocolZipFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignProtocolZipFile", Namespace="http://www.skyline.be/protocolsigning", Order=0)]
        public ProtocolSigningService.SignProtocolZipFileRequestBody Body;
        
        public SignProtocolZipFileRequest()
        {
        }
        
        public SignProtocolZipFileRequest(ProtocolSigningService.SignProtocolZipFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.skyline.be/protocolsigning")]
    public partial class SignProtocolZipFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string connectionGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] protocol;
        
        public SignProtocolZipFileRequestBody()
        {
        }
        
        public SignProtocolZipFileRequestBody(string connectionGuid, byte[] protocol)
        {
            this.connectionGuid = connectionGuid;
            this.protocol = protocol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignProtocolZipFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignProtocolZipFileResponse", Namespace="http://www.skyline.be/protocolsigning", Order=0)]
        public ProtocolSigningService.SignProtocolZipFileResponseBody Body;
        
        public SignProtocolZipFileResponse()
        {
        }
        
        public SignProtocolZipFileResponse(ProtocolSigningService.SignProtocolZipFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.skyline.be/protocolsigning")]
    public partial class SignProtocolZipFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] SignProtocolZipFileResult;
        
        public SignProtocolZipFileResponseBody()
        {
        }
        
        public SignProtocolZipFileResponseBody(byte[] SignProtocolZipFileResult)
        {
            this.SignProtocolZipFileResult = SignProtocolZipFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignProtocolStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignProtocolString", Namespace="http://www.skyline.be/protocolsigning", Order=0)]
        public ProtocolSigningService.SignProtocolStringRequestBody Body;
        
        public SignProtocolStringRequest()
        {
        }
        
        public SignProtocolStringRequest(ProtocolSigningService.SignProtocolStringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.skyline.be/protocolsigning")]
    public partial class SignProtocolStringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string connectionGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string protocol;
        
        public SignProtocolStringRequestBody()
        {
        }
        
        public SignProtocolStringRequestBody(string connectionGuid, string protocol)
        {
            this.connectionGuid = connectionGuid;
            this.protocol = protocol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignProtocolStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignProtocolStringResponse", Namespace="http://www.skyline.be/protocolsigning", Order=0)]
        public ProtocolSigningService.SignProtocolStringResponseBody Body;
        
        public SignProtocolStringResponse()
        {
        }
        
        public SignProtocolStringResponse(ProtocolSigningService.SignProtocolStringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.skyline.be/protocolsigning")]
    public partial class SignProtocolStringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SignProtocolStringResult;
        
        public SignProtocolStringResponseBody()
        {
        }
        
        public SignProtocolStringResponseBody(string SignProtocolStringResult)
        {
            this.SignProtocolStringResult = SignProtocolStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptProtocolZipFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncryptProtocolZipFile", Namespace="http://www.skyline.be/protocolsigning", Order=0)]
        public ProtocolSigningService.EncryptProtocolZipFileRequestBody Body;
        
        public EncryptProtocolZipFileRequest()
        {
        }
        
        public EncryptProtocolZipFileRequest(ProtocolSigningService.EncryptProtocolZipFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.skyline.be/protocolsigning")]
    public partial class EncryptProtocolZipFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string connectionGuid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] protocol;
        
        public EncryptProtocolZipFileRequestBody()
        {
        }
        
        public EncryptProtocolZipFileRequestBody(string connectionGuid, byte[] protocol)
        {
            this.connectionGuid = connectionGuid;
            this.protocol = protocol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptProtocolZipFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncryptProtocolZipFileResponse", Namespace="http://www.skyline.be/protocolsigning", Order=0)]
        public ProtocolSigningService.EncryptProtocolZipFileResponseBody Body;
        
        public EncryptProtocolZipFileResponse()
        {
        }
        
        public EncryptProtocolZipFileResponse(ProtocolSigningService.EncryptProtocolZipFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.skyline.be/protocolsigning")]
    public partial class EncryptProtocolZipFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] EncryptProtocolZipFileResult;
        
        public EncryptProtocolZipFileResponseBody()
        {
        }
        
        public EncryptProtocolZipFileResponseBody(byte[] EncryptProtocolZipFileResult)
        {
            this.EncryptProtocolZipFileResult = EncryptProtocolZipFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface SoapSoapChannel : ProtocolSigningService.SoapSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SoapSoapClient : System.ServiceModel.ClientBase<ProtocolSigningService.SoapSoap>, ProtocolSigningService.SoapSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SoapSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SoapSoapClient.GetBindingForEndpoint(endpointConfiguration), SoapSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SoapSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SoapSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProtocolSigningService.ConnectResponse> ProtocolSigningService.SoapSoap.ConnectAsync(ProtocolSigningService.ConnectRequest request)
        {
            return base.Channel.ConnectAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProtocolSigningService.ConnectResponse> ConnectAsync(string userName, string password, string domain)
        {
            ProtocolSigningService.ConnectRequest inValue = new ProtocolSigningService.ConnectRequest();
            inValue.Body = new ProtocolSigningService.ConnectRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.domain = domain;
            return ((ProtocolSigningService.SoapSoap)(this)).ConnectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProtocolSigningService.LogOutResponse> ProtocolSigningService.SoapSoap.LogOutAsync(ProtocolSigningService.LogOutRequest request)
        {
            return base.Channel.LogOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProtocolSigningService.LogOutResponse> LogOutAsync(string connectionGuid)
        {
            ProtocolSigningService.LogOutRequest inValue = new ProtocolSigningService.LogOutRequest();
            inValue.Body = new ProtocolSigningService.LogOutRequestBody();
            inValue.Body.connectionGuid = connectionGuid;
            return ((ProtocolSigningService.SoapSoap)(this)).LogOutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProtocolSigningService.SignProtocolXmlFileResponse> ProtocolSigningService.SoapSoap.SignProtocolXmlFileAsync(ProtocolSigningService.SignProtocolXmlFileRequest request)
        {
            return base.Channel.SignProtocolXmlFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProtocolSigningService.SignProtocolXmlFileResponse> SignProtocolXmlFileAsync(string connectionGuid, byte[] protocol)
        {
            ProtocolSigningService.SignProtocolXmlFileRequest inValue = new ProtocolSigningService.SignProtocolXmlFileRequest();
            inValue.Body = new ProtocolSigningService.SignProtocolXmlFileRequestBody();
            inValue.Body.connectionGuid = connectionGuid;
            inValue.Body.protocol = protocol;
            return ((ProtocolSigningService.SoapSoap)(this)).SignProtocolXmlFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProtocolSigningService.SignProtocolZipFileResponse> ProtocolSigningService.SoapSoap.SignProtocolZipFileAsync(ProtocolSigningService.SignProtocolZipFileRequest request)
        {
            return base.Channel.SignProtocolZipFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProtocolSigningService.SignProtocolZipFileResponse> SignProtocolZipFileAsync(string connectionGuid, byte[] protocol)
        {
            ProtocolSigningService.SignProtocolZipFileRequest inValue = new ProtocolSigningService.SignProtocolZipFileRequest();
            inValue.Body = new ProtocolSigningService.SignProtocolZipFileRequestBody();
            inValue.Body.connectionGuid = connectionGuid;
            inValue.Body.protocol = protocol;
            return ((ProtocolSigningService.SoapSoap)(this)).SignProtocolZipFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProtocolSigningService.SignProtocolStringResponse> ProtocolSigningService.SoapSoap.SignProtocolStringAsync(ProtocolSigningService.SignProtocolStringRequest request)
        {
            return base.Channel.SignProtocolStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProtocolSigningService.SignProtocolStringResponse> SignProtocolStringAsync(string connectionGuid, string protocol)
        {
            ProtocolSigningService.SignProtocolStringRequest inValue = new ProtocolSigningService.SignProtocolStringRequest();
            inValue.Body = new ProtocolSigningService.SignProtocolStringRequestBody();
            inValue.Body.connectionGuid = connectionGuid;
            inValue.Body.protocol = protocol;
            return ((ProtocolSigningService.SoapSoap)(this)).SignProtocolStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProtocolSigningService.EncryptProtocolZipFileResponse> ProtocolSigningService.SoapSoap.EncryptProtocolZipFileAsync(ProtocolSigningService.EncryptProtocolZipFileRequest request)
        {
            return base.Channel.EncryptProtocolZipFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProtocolSigningService.EncryptProtocolZipFileResponse> EncryptProtocolZipFileAsync(string connectionGuid, byte[] protocol)
        {
            ProtocolSigningService.EncryptProtocolZipFileRequest inValue = new ProtocolSigningService.EncryptProtocolZipFileRequest();
            inValue.Body = new ProtocolSigningService.EncryptProtocolZipFileRequestBody();
            inValue.Body.connectionGuid = connectionGuid;
            inValue.Body.protocol = protocol;
            return ((ProtocolSigningService.SoapSoap)(this)).EncryptProtocolZipFileAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SoapSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SoapSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SoapSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://protocol.skyline.be/api/Soap.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SoapSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://protocol.skyline.be/api/Soap.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SoapSoap,
            
            SoapSoap12,
        }
    }
}
