name: DataMiner CICD NuGet Solution

on:
  push:
    branches: []
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-**"

  workflow_dispatch:

jobs:
  ubuntu-tests:
    name: Run all tests on Ubuntu
    runs-on: ubuntu-22.04 # Latest misses mono for .NET Framework
    env:
      azure-key-vault-certificate: ${{ secrets.AZURE_KEY_VAULT_CERTIFICATE }}
      azure-key-vault-url: ${{ secrets.AZURE_KEY_VAULT_URL }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4
        
      - name: Test
        run: dotnet test -c Release --filter TestCategory!=Windows
        

  dotnet-test:
    name: Run Integration Tests
    runs-on: windows-latest
    env:
      azure-key-vault-certificate: ${{ secrets.AZURE_KEY_VAULT_CERTIFICATE }}
      azure-key-vault-url: ${{ secrets.AZURE_KEY_VAULT_URL }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Integration Tests
        run: dotnet test -c Release --filter TestCategory=IntegrationTest
        continue-on-error: true

  # CICD:
  #   needs: [ubuntu-tests, dotnet-test]
  #   uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/NuGet Solution Master Workflow.yml@main
  #   with:
  #     referenceName: ${{ github.ref_name }}
  #     runNumber: ${{ github.run_number }}
  #     referenceType: ${{ github.ref_type }}
  #     repository: ${{ github.repository }}
  #     owner: ${{ github.repository_owner }}
  #     sonarCloudProjectName: SkylineCommunications_Skyline.DataMiner.CICD.Tools.PackageSign
  #   secrets:
  #     sonarCloudToken: ${{ secrets.SONAR_TOKEN }}
  #     pfxPassword: ${{ secrets.PFXPASSWORD }}
  #     nugetApiKey: ${{ secrets.NUGETAPIKEY }}